# Generated by Django 3.1.2 on 2023-03-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20230307_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='school.Teacher', verbose_name='Учитель'),
        ),
    ]
